[package]
name = "update-repo"
version = "0.1.0"
authors = ["Mike Bush <platy@njk.onl>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
url = "2.2.0"

[dev-dependencies]
anyhow = "1.0.40"
chrono-tz = "0.5.3"
clap = "2.33.3"
