apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smtp-dump
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: update-tracker
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-tracker
spec:
  selector:
    matchLabels:
      app: update-tracker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: update-tracker
    spec:
      containers:
      - name: smtp-dump
        image: rg.nl-ams.scw.cloud/njkonl/smtp-dump:0.1.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "80Mi"
            cpu: "50m"
        ports:
        - containerPort: 25
          hostPort: 25
        volumeMounts:
          - mountPath: "/mail"
            name: mail
        env:
          - name: INBOX_DIR
            value: /mail/inbox
          - name: TEMP_DIR
            value: /mail/tmp
      - name: update-tracker
        image: rg.nl-ams.scw.cloud/njkonl/update-tracker:0.1.6
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "80Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/mail"
            name: mail
          - mountPath: "/updates"
            name: updates
        env:
          - name: INBOX
            value: /mail/inbox/mail.notifications.service.gov.uk
          - name: OUTBOX
            value: /mail/outbox/mail.notifications.service.gov.uk
          - name: NEW_REPO
            value: /updates/repo
          - name: GIT_REPO
            value: /updates/gitgovuk
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: mail
          persistentVolumeClaim:
            claimName: smtp-dump
        - name: updates
          persistentVolumeClaim:
            claimName: update-tracker

---

apiVersion: v1
kind: Service
metadata:
  name: update-tracker
spec:
  selector:
    app: update-tracker
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: update-tracker
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: update-tracker.njk.onl
    http:
      paths:
      - path: /
        backend:
          service:
            name: update-tracker
            port:
              number: 80
        pathType: Prefix
  tls:
  - hosts:
    - update-tracker.njk.onl
    secretName: update-tracker-cert

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: update-tracker
spec:
  dnsNames:
  - update-tracker.njk.onl
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: update-tracker-cert
