apiVersion: v1
kind: Pod
metadata:
  name: sshd
spec:
  containers:
  - name: sshd
    image: panubo/sshd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "80Mi"
        cpu: "50m"
    env:
      - name: SSH_ENABLE_ROOT
        value: 'true'
    ports:
    - containerPort: 22
    volumeMounts:
      - mountPath: "/share/mail"
        name: mail
      - mountPath: "/share/updates"
        name: updates
      - mountPath: /root/.ssh/authorized_keys
        name: authorized-keys
        subPath: authorized_keys
  imagePullSecrets:
  - name: regcred
  volumes:
    - name: mail
      persistentVolumeClaim:
        claimName: smtp-dump
    - name: updates
      persistentVolumeClaim:
        claimName: update-tracker
    - name: authorized-keys
      configMap:
        name: ssh-authorized-keys

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-authorized-keys
  namespace: default
data:
  authorized_keys: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCs1JZA0pHL1mxLCft4XgQHSvcx3aPTsR2HbRWbh0bEWELX/o2AbM0SdZSku+9SQhAALoeWFSgsptiTa3KPhCyYQRA/Q2UfCsoFXn5Nfr6OFWR2LnP5t6q9cJM2WkFdXr00lENmy6XWuBhxTBB6AQ5am6+B2jmhSMEuHyWH87fLg1tWtpxRuxPMmwyQCGtNSGk3NJQ3KdlKQqqtMSrOD/yuK60IvTZGaMF5IQkVJVqqHaa1DMzbwq8++OuG2jYg7V8S3z1nz/RCLr9mfEKZipTkrJctJYR414FdIQs45JaKpuieGAfsP8B9yT7DS6eZsyadj1VtvqsJNs7W7RQ/iWIgiuBt0UvBINGRkN18wK3PN86iI5lCjzBTOZIemLvkjbeAfuiPKNse4JyWf2DReV22LS0W05XL392Bm4Sp/7G26lGUpenFO511ExdEGKxBYurLJGBFLgGuTXTlOBcGd9a3G8Ho8oAW8SDdZ0bccG2dTdvhXAdragx3UN5sHF4Sx5p3698iyYRIEA7HT1sboajWkC0ievGWkuWJAAifHOpEqmLWia5KeWuq3dsN6Q/r2ID0uNKs/DhOgucmKBjR1jDduZtVrQWA6sATN/l8sa5gcN5/L5Hfx87Kkz3Q1l7BaPskE7jwuoPBaSHD/kJEYbrWSHqGZdOw9o1oJYPJ02aNQQ== mike@Marney
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGoIIauYvOlIaARfMwBaEUCraTfuLt38bRtstrt9m4gY mike@Volta
