[package]
name = "update-tracker"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4.19"
form_urlencoded = "1.0.1"
htmldiff = "0.1.0"
rouille = "3.3.1"
tantivy = "0.16.1" # probly-search or simsearch might be interesting here instead
update-repo = { path = ".." }
url = "2.2.2"
