[package]
name = "update-tracker"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4.19"
form_urlencoded = "1.0.1"
htmldiff = "0.1.0"
qp-trie = "0.7.7"
rouille = "3.3.1"
simsearch = "0.2.3"
update-repo = { path = ".." }
url = "2.2.2"
